INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title1", "Real Estate", 10000, "9/19", "12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title2", "Real Estate", 300000, "12/19", "11/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title3", "Space Exploration", 9000000, "9/19", "12/25");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title4", "Science", 100000, "9/19", "12/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title5", "Science", 500000, "9/19", "12/29");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title6", "Science", 192000, "9/19", "12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title7", "Time Travel", 8888888, "9/19", "12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title8", "Finance", 999000, "9/19", "4/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title9", "Finance", 100300, "9/19", "12/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Title10", "Retail", 590000, "9/19", "12/20");


INSERT INTO users (name, age) VALUES ("Bob", 35);
INSERT INTO users (name, age) VALUES ("Jane", 29);
INSERT INTO users (name, age) VALUES ("Mike", 45);
INSERT INTO users (name, age) VALUES ("Hank", 29);
INSERT INTO users (name, age) VALUES ("User5", 35);
INSERT INTO users (name, age) VALUES ("User6", 33);
INSERT INTO users (name, age) VALUES ("User7", 25);
INSERT INTO users (name, age) VALUES ("User8", 24);
INSERT INTO users (name, age) VALUES ("User9", 20);
INSERT INTO users (name, age) VALUES ("User10", 21);
INSERT INTO users (name, age) VALUES ("User11", 21);
INSERT INTO users (name, age) VALUES ("User12", 25);
INSERT INTO users (name, age) VALUES ("User13", 25);
INSERT INTO users (name, age) VALUES ("User14", 27);
INSERT INTO users (name, age) VALUES ("User15", 24);
INSERT INTO users (name, age) VALUES ("User16", 26);
INSERT INTO users (name, age) VALUES ("User17", 22);
INSERT INTO users (name, age) VALUES ("User18", 31);
INSERT INTO users (name, age) VALUES ("User19", 32);
INSERT INTO users (name, age) VALUES ("User20", 33);

INSERT into pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 1, 2);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 2, 3);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 3, 4);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 4, 5);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 5, 6);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 6, 7);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 7, 8);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 8, 9);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 9, 10);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 10, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 11, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 12, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 13, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 14, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 15, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 16, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 17, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 18, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 19, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 20, 1);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 3, 3);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 4, 4);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 5, 5);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 6, 6);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 7, 7);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 8, 8);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 9, 9);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT into pledges (amount, user_id, project_id) VALUES (50, 17, 10);